FROM openjdk:12.0.1-jdk

MAINTAINER William Custodio

ARG JAR_FILE

ENV PRODUCT_AUTH_CHECK_TOKEN_URL=''
ENV PRODUCT_AUTH_CLIENT_ID=''
ENV PRODUCT_AUTH_CLIENT_SECRET=''

ENV PRODUCT_MONGODB_DATABASE=''
ENV PRODUCT_MONGODB_AUTHENTICATION_DATABASE=''
ENV PRODUCT_MONGODB_DATABASE_URI=''

ENV PRODUCT_MESSAGE_BROKER_URL=''
ENV PRODUCT_MESSAGE_BROKER_USER=''
ENV PRODUCT_MESSAGE_BROKER_PASSWORD=''
ENV PRODUCT_MESSAGE_BROKER_OUTCOME_QUEUE=''

COPY $JAR_FILE rest-house-product-api.jar

ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -jar rest-house-product-api.jar