#####################################
###  TOMCAT SERVER CONFIGURATION ####
#####################################
server:
  port: 8082
  servlet:
    context-path: /api
#####################################
##  Resource Server Configuration ###
#####################################
spring:
  security:
    oauth2:
      resource-server:
        id: RestHouseProductApi
        check-token-url: ${PRODUCT_AUTH_CHECK_TOKEN_URL}
      client:
        id: ${PRODUCT_AUTH_CLIENT_ID}
        secret: ${PRODUCT_AUTH_CLIENT_SECRET}
  #####################################
  ####  Data Source Configuration #####
  #####################################
  data:
    mongodb:
      database: ${PRODUCT_MONGODB_DATABASE}
      authentication-database: ${PRODUCT_MONGODB_AUTHENTICATION_DATABASE}
      uri: ${PRODUCT_MONGODB_DATABASE_URI}
  #####################################
  #####  Publisher Configuration ######
  #####################################
  gcp:
    topic-id: ${GOOGLE_CLOUD_PROJECT_TOPIC}