version: '3'

services:
  rest-house-authorization-server:
    image: williamcustodio/rest-house-authorization-server:latest
    environment:
      - AUTH_DATASOURCE_URL=jdbc:postgresql://authorization-database:5432/rest-house-authorization
      - AUTH_DATASOURCE_USERNAME=rest-house
      - AUTH_DATASOURCE_PASSWORD=rest-house
      - AUTH_FLYWAY_SCRIPT_LOCATION=classpath:database
    ports:
      - "8080:8080"
    networks:
      - rest-house-network
    depends_on:
      - authorization-database
  authorization-database:
    image: postgres:latest
    container_name: authorization-database
    restart: always
    environment:
      POSTGRES_PASSWORD: rest-house
      POSTGRES_USER: rest-house
      POSTGRES_DB: rest-house-authorization
    ports:
      - "5432:5432"
    networks:
      - rest-house-network
  product-database:
    image: mongo:latest
    container_name: product-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rest-house
      MONGO_INITDB_ROOT_PASSWORD: rest-house
    ports:
      - "27017:27017"
    volumes:
      - "/tmp/productDatabase:/data/db"
networks:
  rest-house-network:
    driver: bridge